/*
 * This source file was generated by the Gradle 'init' task
 */
package text.based.adventure.game;

public class App {
    public static void main(String[] args) {
        Game game = new Game();
        game.start();
    }
    }
    
